services:
  orbslam3-spell:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      -  DISPLAY=${DISPLAY}
    volumes:
      - ../src:/app
      - ../config:/config
      - ../data:/root/Datasets/
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../output:/root/output
    working_dir: /root
    stdin_open: true # docker run -i
    tty: true # docker run -t  