version: "3.8"

services:
  obrslam3-spell:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../src:/app
      - ../config:/config
      - ../data/EuRoc/MH01:/data/MH01
    working_dir: /app
    stdin_open: true # docker run -i
    tty: true # docker run -t